kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${SERVICE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      name: ${SERVICE_NAME}
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${SERVICE_NAME}
          resources:
            limits:
              memory: 128Mi
              cpu: "0.5"
            requests:
              memory: 64Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 18080
              protocol: TCP
      imagePullSecrets:
        - name: ghcr
